name: "Samsung Frame Art Rotator"
version: "1.0.0"
slug: "samsung_frame_art_rotator"
description: "Daily rotation of Immich album images on Samsung Frame TV (Art Mode)."
url: "https://github.com/chermeschaterne/ha-samsung-frame-art-rotator"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
init: false
startup: services
boot: auto
hassio_api: false
homeassistant_api: true
host_network: false
auth_api: false
ingress: true
panel_icon: "mdi:image-multiple"
panel_title: "Frame Art Rotator"
panel_admin: false
ports: {}
ports_description: {}
map:
  - addon_config:rw
options:
  immich:
    share_url: "https://immich.chanluto.de/share/nB7yPpVHisCg4hMHOdIuA1ZzWtku6bb5fdxW1_X6-EkSeVVqBOrCVDUyvYHpY40"
  samsung_frame:
    host: "192.168.2.92"
    mac: "38:8c:ef:bb:b4:8c"
    client_name: "HermesFrame"
    matte: "flexible_apricot"
  schedule:
    enabled: true
    rotation_time: "06:00"
  brightness:
    level: 2
    disable_sensor: true
    motion_sensor: ""
    motion_timeout_minutes: 15
schema:
  immich:
    share_url: url
  samsung_frame:
    host: "match(^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$)"
    mac: "match(^[0-9a-fA-F:]{17}$)"
    client_name: str
    matte: "list(none|modernthin|modern|modernwide|flexible|shadowbox|panoramic|triptych|mix|squares|flexible_apricot|flexible_black|flexible_white|shadowbox_warm|shadowbox_cool|modernthin_black|modern_apricot|modernwide_burgandy|triptych_black|squares_sage|squares_seafoam)"
  schedule:
    enabled: bool
    rotation_time: time
  brightness:
    level: "int(1,10)"
    disable_sensor: bool
    motion_sensor: "str?"
    motion_timeout_minutes: "int(1,120)"
